### ISSUE TITLE
Distributed training error

### ISSUE THREAD

**Issue by KlaineWei** [twinkle0331/LGTM#4]
Hi, I try to use two gpus on one machine to run the run_glue.py, but it meets an distributed error,below is my running scripts in the bash file:
```console
export OUT_DIR=./saved/
CUDA_VISIBLE_DEVICES=0,1
python -m torch.distributed.launch \
    --nproc_per_node 2 run_glue.py \
    --model_name_or_path google/bert_uncased_L-6_H-768_A-12 \
    --teacher_model bert-base-uncased \
    --task_name mnli \
    --per_device_train_batch_size 128 \
    --per_device_eval_batch_size 128 \
    --learning_rate 3e-05 \
    --t_learning_rate 3e-05 \
    --alpha_kd 1.0 \
    --temperature 1.0 \
    --num_train_epochs 6 \
    --output_dir $OUT_DIR \
    --overwrite_output_dir \
    --eval_steps 1000 \
    --do_train \
    --do_eval \
    --train_teacher \
    --init_classifier_to_zero \
    --use_lgtm
```

and the error is:
```console
06/27/2023 00:48:29 - INFO - __main__ - ***** Evaluation Results*****
06/27/2023 00:48:29 - INFO - __main__ -   Training step = 1000
06/27/2023 00:48:29 - INFO - __main__ -  eval_accuracy:0.7537442689760571 
[INFO|tokenization_utils_base.py:2145] 2023-06-27 00:48:29,178 >> tokenizer config file saved in ./saved/tokenizer_config.json
[INFO|tokenization_utils_base.py:2152] 2023-06-27 00:48:29,178 >> Special tokens file saved in ./saved/special_tokens_map.json
Traceback (most recent call last):
  File "run_glue.py", line 830, in <module>
    main()
  File "run_glue.py", line 789, in main
    model.save_pretrained(training_args.output_dir)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
Traceback (most recent call last):
  File "run_glue.py", line 830, in <module>
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'save_pretrained'
    main()
  File "run_glue.py", line 789, in main
    model.save_pretrained(training_args.output_dir)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'save_pretrained'
```

It seems like the model doesn't support distributed training so it meets error in the evaluation step. Is there anything wrong with my scripts? What is your distributed training scripts? Thanks!

**Comment by twinkle0331** [comment]
Since the training for downstream task is not expensive, so we did not use distributed training. The experiments were performed on Tesla V100 and T4 GPU.  If you want to modify the code to enable distributed training, you can refer to [link](https://github.com/huggingface/transformers/issues/16971) and change `model.save_pretrained(<directory>)` to be `model.module.save_pretrained(<directory>)`. The error is because that `model` is wrapped by `DistributedDataParallel `, but `DistributedDataParallel` object has no attribute `save_pretrained`.

**Comment by twinkle0331** [comment]
I closed the issue, feel free to reopen it if you have further questions.
